# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 160)
        Form.setMaximumSize(QtCore.QSize(16777215, 160))
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 480, 160))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.reset_ui = QtWidgets.QPushButton(self.frame)
        self.reset_ui.setGeometry(QtCore.QRect(325, 10, 140, 40))
        self.reset_ui.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.reset_ui.setObjectName("reset_ui")
        self.create_gift_wall_file = QtWidgets.QPushButton(self.frame)
        self.create_gift_wall_file.setGeometry(QtCore.QRect(325, 60, 140, 40))
        self.create_gift_wall_file.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.create_gift_wall_file.setObjectName("create_gift_wall_file")
        self.reload_data_config = QtWidgets.QPushButton(self.frame)
        self.reload_data_config.setGeometry(QtCore.QRect(15, 10, 140, 40))
        self.reload_data_config.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.reload_data_config.setObjectName("reload_data_config")
        self.reload_data = QtWidgets.QPushButton(self.frame)
        self.reload_data.setGeometry(QtCore.QRect(170, 10, 140, 40))
        self.reload_data.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.reload_data.setObjectName("reload_data")
        self.clear_outputs = QtWidgets.QPushButton(self.frame)
        self.clear_outputs.setGeometry(QtCore.QRect(170, 110, 140, 40))
        self.clear_outputs.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.clear_outputs.setObjectName("clear_outputs")
        self.add_gift_wall = QtWidgets.QPushButton(self.frame)
        self.add_gift_wall.setGeometry(QtCore.QRect(15, 60, 140, 40))
        self.add_gift_wall.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.add_gift_wall.setObjectName("add_gift_wall")
        self.open_outputs = QtWidgets.QPushButton(self.frame)
        self.open_outputs.setGeometry(QtCore.QRect(15, 110, 140, 40))
        self.open_outputs.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.open_outputs.setObjectName("open_outputs")
        self.import_gift_wall = QtWidgets.QPushButton(self.frame)
        self.import_gift_wall.setGeometry(QtCore.QRect(170, 60, 140, 40))
        self.import_gift_wall.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"微软雅黑\";")
        self.import_gift_wall.setObjectName("import_gift_wall")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.reset_ui.setText(_translate("Form", "重置界面"))
        self.create_gift_wall_file.setText(_translate("Form", "生成GiftWall"))
        self.reload_data_config.setText(_translate("Form", "重下载服务器配置表"))
        self.reload_data.setText(_translate("Form", "重下载服务器数据"))
        self.clear_outputs.setText(_translate("Form", "清空Outputs"))
        self.add_gift_wall.setText(_translate("Form", "添加GiftWall"))
        self.open_outputs.setText(_translate("Form", "查看Outputs"))
        self.import_gift_wall.setText(_translate("Form", "导入GiftWall"))
