# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_language.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(669, 110)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_name_title = QtWidgets.QLabel(Form)
        self.file_name_title.setMinimumSize(QtCore.QSize(120, 40))
        self.file_name_title.setMaximumSize(QtCore.QSize(120, 40))
        self.file_name_title.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);")
        self.file_name_title.setAlignment(QtCore.Qt.AlignCenter)
        self.file_name_title.setObjectName("file_name_title")
        self.horizontalLayout.addWidget(self.file_name_title)
        self.file_name = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_name.sizePolicy().hasHeightForWidth())
        self.file_name.setSizePolicy(sizePolicy)
        self.file_name.setMinimumSize(QtCore.QSize(0, 40))
        self.file_name.setMaximumSize(QtCore.QSize(16777215, 40))
        self.file_name.setStyleSheet("font: 14pt \"微软雅黑\";\n"
"color: rgb(85, 85, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.file_name.setText("")
        self.file_name.setAlignment(QtCore.Qt.AlignCenter)
        self.file_name.setObjectName("file_name")
        self.horizontalLayout.addWidget(self.file_name)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.language_title = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language_title.sizePolicy().hasHeightForWidth())
        self.language_title.setSizePolicy(sizePolicy)
        self.language_title.setMinimumSize(QtCore.QSize(120, 40))
        self.language_title.setMaximumSize(QtCore.QSize(120, 40))
        self.language_title.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);")
        self.language_title.setAlignment(QtCore.Qt.AlignCenter)
        self.language_title.setObjectName("language_title")
        self.horizontalLayout_2.addWidget(self.language_title)
        self.language = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.language.sizePolicy().hasHeightForWidth())
        self.language.setSizePolicy(sizePolicy)
        self.language.setMinimumSize(QtCore.QSize(0, 40))
        self.language.setMaximumSize(QtCore.QSize(16777215, 40))
        self.language.setStyleSheet("font: 14pt \"微软雅黑\";\n"
"color: rgb(85, 85, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.language.setText("")
        self.language.setAlignment(QtCore.Qt.AlignCenter)
        self.language.setObjectName("language")
        self.horizontalLayout_2.addWidget(self.language)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_2.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        # self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.file_name_title.setText(_translate("Form", "选择输出文件名"))
        self.pushButton.setText(_translate("Form", "选择"))
        self.language_title.setText(_translate("Form", "选择输出地区"))
        self.pushButton_2.setText(_translate("Form", "选择"))
