# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_update_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 120))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 180, 60))
        self.label.setStyleSheet("font: 18pt \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.latest_version = QtWidgets.QLineEdit(self.frame)
        self.latest_version.setGeometry(QtCore.QRect(220, 30, 180, 60))
        self.latest_version.setStyleSheet("font: 18pt \"微软雅黑\";\n"
"color: rgb(57, 61, 255);")
        self.latest_version.setAlignment(QtCore.Qt.AlignCenter)
        self.latest_version.setObjectName("latest_version")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.content = QtWidgets.QWidget()
        self.content.setGeometry(QtCore.QRect(0, 0, 1276, 602))
        self.content.setMinimumSize(QtCore.QSize(0, 0))
        self.content.setObjectName("content")
        self.scrollArea.setWidget(self.content)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.open_to = QtWidgets.QPushButton(Form)
        self.open_to.setMinimumSize(QtCore.QSize(180, 60))
        self.open_to.setMaximumSize(QtCore.QSize(180, 60))
        self.open_to.setStyleSheet("font: 18pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);")
        self.open_to.setObjectName("open_to")
        self.horizontalLayout.addWidget(self.open_to)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.save_to = QtWidgets.QPushButton(Form)
        self.save_to.setMinimumSize(QtCore.QSize(180, 60))
        self.save_to.setStyleSheet("font: 18pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);")
        self.save_to.setObjectName("save_to")
        self.horizontalLayout.addWidget(self.save_to)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "最新版本号"))
        self.open_to.setText(_translate("Form", "读取文件"))
        self.save_to.setText(_translate("Form", "保存到"))
