# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1400, 720)
        Form.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(80, 0))
        self.frame.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame.setStyleSheet("background-color: rgb(57, 61, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.icon = QtWidgets.QLabel(self.frame)
        self.icon.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        self.menu_layout_1 = QtWidgets.QFrame(self.frame)
        self.menu_layout_1.setGeometry(QtCore.QRect(0, 140, 80, 100))
        self.menu_layout_1.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.menu_layout_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_layout_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_layout_1.setObjectName("menu_layout_1")
        self.menu_icon_1 = QtWidgets.QLabel(self.menu_layout_1)
        self.menu_icon_1.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.menu_icon_1.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_icon_1.setObjectName("menu_icon_1")
        self.menu_title_1 = QtWidgets.QLabel(self.menu_layout_1)
        self.menu_title_1.setGeometry(QtCore.QRect(0, 70, 80, 20))
        self.menu_title_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 8pt \"微软雅黑\";")
        self.menu_title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_title_1.setObjectName("menu_title_1")
        self.menu_layout_2 = QtWidgets.QFrame(self.frame)
        self.menu_layout_2.setGeometry(QtCore.QRect(0, 240, 80, 100))
        self.menu_layout_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_layout_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_layout_2.setObjectName("menu_layout_2")
        self.menu_icon_2 = QtWidgets.QLabel(self.menu_layout_2)
        self.menu_icon_2.setGeometry(QtCore.QRect(20, 20, 40, 40))
        self.menu_icon_2.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_icon_2.setObjectName("menu_icon_2")
        self.menu_title_2 = QtWidgets.QLabel(self.menu_layout_2)
        self.menu_title_2.setGeometry(QtCore.QRect(0, 70, 80, 20))
        self.menu_title_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"微软雅黑\";")
        self.menu_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_title_2.setObjectName("menu_title_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 80, 80, 30))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.icon.setText(_translate("Form", "1"))
        self.menu_icon_1.setText(_translate("Form", "2"))
        self.menu_title_1.setText(_translate("Form", "广告工具"))
        self.menu_icon_2.setText(_translate("Form", "2"))
        self.menu_title_2.setText(_translate("Form", "应用升级工具"))
        self.label.setText(_translate("Form", "iJoySoft"))
