# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 50)
        Form.setStyleSheet("")
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setContentsMargins(0, 0, 0, 6)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 42))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pb_edit_gift = QtWidgets.QPushButton(self.frame)
        self.pb_edit_gift.setGeometry(QtCore.QRect(0, 0, 180, 42))
        self.pb_edit_gift.setMinimumSize(QtCore.QSize(180, 42))
        self.pb_edit_gift.setStyleSheet("font: 16pt \"微软雅黑\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pb_edit_gift.setFlat(False)
        self.pb_edit_gift.setObjectName("pb_edit_gift")
        self.pb_app_update = QtWidgets.QPushButton(self.frame)
        self.pb_app_update.setGeometry(QtCore.QRect(180, 0, 180, 42))
        self.pb_app_update.setMinimumSize(QtCore.QSize(180, 42))
        self.pb_app_update.setStyleSheet("font: 16pt \"微软雅黑\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pb_app_update.setFlat(False)
        self.pb_app_update.setObjectName("pb_app_update")
        self.horizontalLayout.addWidget(self.frame)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_edit_gift.setText(_translate("Form", "广告配置"))
        self.pb_app_update.setText(_translate("Form", "应用升级配置"))
